export const ADD_TO_CART = 'ADD_TO_CART'
export const SUB_FROM_CART = 'SUB_FROM_CART'
export const DEL_FROM_CART = 'DEL_FROM_CART'
export const RECEIVE_ITEMS = 'RECEIVE_ITEMS'
export const SELECT_ITEM = 'SELECT_ITEM'